CXX = g++
CXXFLAGS = -Wall 

all : template template_classe template_class_special

template : template.cpp 

template_classe : template_classe.cpp

template_class_special : template_class_special.cpp
