CXX = g++
CXXFLAGS = -Wall 

all : class_example test_friend correction_Basile_double_linked liste_doublement_chainee

class_example : class_example.cpp

test_friend : test_friend.cpp

correction_Basile_double_linked : correction_Basile_double_linked.cpp

liste_doublement_chainee : liste_doublement_chainee.cpp

clean:
	rm test_friend
	rm class_example
	rm liste_doublement_chainee
	rm correction_Basile_double_linked