CXX = g++
CXXFLAGS = -Wall 

all : std_container std_algorithm classes_remember std_fstream

std_container : std_container.cpp
std_algorithm : std_algorithm.cpp
classes_remember : classes_remember.cpp
std_fstream : std_fstream.cpp

clean :
	rm std_container
	rm std_algorithm
	rm classes_remember
	rm std_fstream