CXX = g++
CXXFLAGS = -Wall 

all : std_container std_algorithm

std_container : std_container.cpp
std_algorithm : std_algorithm.cpp
classes_remember : classes_remember.cpp

clean :
	rm std_container
	rm std_algorithm